### ISSUE TITLE
popupclose and popupopen events

### ISSUE THREAD

**Issue by WimAtIHomer** [binhums/ember-cli-mapbox#17]
@bdvholmes thanx for the new release.
I have one small request can you add the popupclose and popupopen events to the mapbox-marker component? 
I am using these events to inject an ember component into the popup with https://github.com/yapplabs/ember-wormhole.

**Comment by bdvholmes** [comment]
Looks good to me. Needs to be able to specify actions to trigger on `mapbox-marker`

http://leafletjs.com/reference.html#marker-popupopen
http://leafletjs.com/reference.html#marker-popupclose

If anyone starts implementing this, consider adding support for:

  1. All events in the events list, and
  2. specifying events for the `mapbox-map` component too.

**Comment by bdvholmes** [comment]
@WimAtIHomer check out #21, it's pretty easy to implement hooks for these events. You'd just need to add them to mapbox-marker instead, if you're interested in contributing. If not I'll just do it.

What do you think?

**Comment by WimAtIHomer** [comment]
Added two pull-requests one for this issue and one for center and resize.

**Comment by binhums** [comment]
Fixed by #22
