### ISSUE TITLE
marker click action should send latlng

### ISSUE THREAD

**Issue by andrewfan** [binhums/ember-cli-mapbox#24]
https://github.com/binhums/ember-cli-mapbox/blob/master/addon/components/mapbox-marker.js#L33
should be updated to send marker's latlng
```
marker.on('click', (e) => {
      this.sendAction('onclick', e.latlng);
    });
```
@binhums  if you want i can make PR

**Comment by binhums** [comment]
@andrewfan I actually think it would be better to just send the marker up and then that gives the developer access to whatever they need, e.g. `latlng`. So something along the lines of

```js
marker.on('click', (e) => {
      this.sendAction('onclick', e);
    });
```

or maybe

```js
marker.on('click', () => {
      this.sendAction('onclick', this.get('marker'));
    });
```

Please do make a PR with something appropriate :+1:

**Comment by binhums** [comment]
#31 for inspiration. I'm going to implement the equivalent on markers.

**Comment by binhums** [comment]
Opened #32

**Comment by binhums** [comment]
Released https://github.com/binhums/ember-cli-mapbox/releases/tag/v0.3.2

@andrewfan should be fixed for you.
