### ISSUE TITLE
Breaks on new ember-cli

### ISSUE THREAD

**Issue by borisrorsvort** [binhums/ember-cli-mapbox#34]
![1 _borislittlefinger_sitesmycollecto_zsh_2016-03-03_17-14-07](https://cloud.githubusercontent.com/assets/39081/13500573/6b8be2f4-e163-11e5-9315-83e8c06a9d30.png)

**Comment by mileszim** [comment]
![screen shot 2016-03-03 at 11 24 38 am](https://cloud.githubusercontent.com/assets/1849508/13506575/9d886d48-e133-11e5-9b88-3144aaf84fba.png)

Reproduced, got a little more descriptive error.

**Comment by binhums** [comment]
Thanks everyone!

**Comment by binhums** [comment]
Released [0.3.3](https://github.com/binhums/ember-cli-mapbox/releases/tag/v0.3.3)
