### ISSUE TITLE
Map tiles not loading

### ISSUE THREAD

**Issue by kyleicebreaker** [binhums/ember-cli-mapbox#39]
![screen shot 2016-04-06 at 11 01 21 am](https://cloud.githubusercontent.com/assets/14184138/14327662/257e6652-fbe8-11e5-92e2-5bef22bb9b26.png)

Map is blank, no tiles are being loaded. Map is sized correctly and I can see the translation updates on the DOM element when dragging around on empty white space. JSON from mapbox looks okay. Only thing that looks funky is the center property. Any ideas?

##### Handlebars Template
```hbs
{{mapbox-map
  mapId='kjalwyn.pk23bmpg'
  divId='mega-map'
  center=(mapbox-coords 37.768 -122.381)
  zoom=13
}}
```

##### JSON from Mapbox
```js
{
  "attribution": "<a href=\"https:\/\/www.mapbox.com\/about\/maps\/\" target=\"_blank\">&copy; Mapbox<\/a> <a href=\"https:\/\/openstreetmap.org\/about\/\" target=\"_blank\">&copy; OpenStreetMap<\/a> <a class=\"mapbox-improve-map\" href=\"https:\/\/www.mapbox.com\/map-feedback\/\" target=\"_blank\">Improve this map<\/a>",
  "autoscale": true,
  "bounds": [
    -180,
    -85,
    180,
    85
  ],
  "center": [
    0,
    0,
    3
  ],
  "created": 1459961311046,
  "data": [
    "http:\/\/a.tiles.mapbox.com\/v4\/kjalwyn.pk23bmpg\/features.json?access_token=pk.Fx9y58FZHE3RTpbkgGHryQ"
  ],
  "dataset": "cimp39pxz00oju7lyjv0mbcwb",
  "description": "",
  "id": "kjalwyn.pk23bmpg",
  "mapbox_logo": true,
  "maxzoom": 19,
  "minzoom": 0,
  "modified": 1459961312498,
  "name": "Untitled project",
  "private": false,
  "scheme": "xyz",
  "tilejson": "2.0.0",
  "tiles": [
    "http:\/\/a.tiles.mapbox.com\/v4\/kjalwyn.pk23bmpg\/{z}\/{x}\/{y}.png?access_token=pk.Fx9y58FZHE3RTpbkgGHryQ",
    "http:\/\/b.tiles.mapbox.com\/v4\/kjalwyn.pk23bmpg\/{z}\/{x}\/{y}.png?access_token=pk.Fx9y58FZHE3RTpbkgGHryQ"
  ],
  "webpage": "http:\/\/a.tiles.mapbox.com\/v4\/kjalwyn.pk23bmpg\/page.html?access_token=pk.Fx9y58FZHE3RTpbkgGHryQ"
}
```

**Comment by kyleicebreaker** [comment]
This had to do with ember-cli-mirage, not your lib.

**Comment by binhums** [comment]
Thanks for raising anyway. Are you able to get ember-cli-mirage working with this addon @kyleicebreaker ?

**Comment by kyleicebreaker** [comment]
Had to move on for the day and get to real work as this is just for a side proj to learn ember but will continue trying later. I read a few issues related to mirage intercepting asset requests which makes sense for this issue. Tried to add passthroughs for all variations of mapbox urls to no avail. I'll update if I can get it working but for now I had to disable the addon.

**Comment by binhums** [comment]
Got it. If it helps at all you can access the pretender instance directly within Mirage if you can't get it working with Mirage's interface. I think through something like `server.pretender`.

It's low level but might help you achieve what you need.
